name: coda_wallet
description: Staking-Power wallet worked for Mina on both android and ios, developed by flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^4.0.0-beta.1
  bloc: ^6.0.0
  flutter_bloc: ^6.0.5
  equatable: ^1.1.1
  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.0.13
  flutter_screenutil: ^3.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.12+2
  keyboard_actions: "^3.3.1+1"
  image_gallery_saver: '^1.6.5'
  permission_handler: ^5.0.1+1
  percent_indicator: '^2.1.9'
  event_bus: '^1.1.1'
  top_k: '^1.0.1'
  common_utils: ^1.2.1
  url_launcher: ^5.7.10
  package_info: ^0.4.3+4
  dio: ^3.0.10
  cached_network_image: ^2.5.0
#  flip_panel: '^1.0.1'
  ffi_mina_signer:
    path: ../ffi_mina_signer/

dev_dependencies:
  flutter_test:
    sdk: flutter
  gql_code_gen: ^0.1.5
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - copy_gray.png
    - images/wallet_tab_unselected.png
    - images/wallet_tab_selected.png
    - images/txns_tab_selected.png
    - images/txns_tab_unselected.png
    - images/stake_tab_unselected.png
    - images/stake_tab_selected.png
    - images/settings_tab_selected.png
    - images/settings_tab_unselected.png
    - images/mina_logo_inner.png
    - images/qr_code_icon.png
    - images/wallet_staked_bg.png
    - images/to_stake_flower.png
    - images/no_staking_bg.png
    - images/back.png
    - images/common_bg.png
    - images/mina_logo_black_inner.png
    - images/account_header.png
    - images/pool_header.png
    - images/qr_scanner.png
    - images/close.png
    - images/sent_success.png
    - images/fee_selected.png
    - images/txn_send.png
    - images/txn_receive.png
    - images/txn_stake.png
    - images/txn_pending.png
    - images/txn_filter.png
    - images/filter_logo.png
    - images/down_expand.png
    - images/arrow_right.png
    - images/create_account.png
    - images/input_delete.png
    - images/password_lock_logo.png
    - images/password_hide.png
    - images/password_show.png
    - images/password_unlock_logo.png
    - images/import_wallet_bg.png
    - images/mina_logo_white_trans.png
    - images/security_alert_blue.png
    - images/security_alert_gray.png
    - images/pwd_show.png
    - images/pwd_hide.png
    - images/new_wallet_alert.png
    - images/send_error_alert.png
    - images/txns_no_data.png
    - images/security_alert_gold.png
    - images/stake_logo_deep_color.png

  fonts:
   - family: Entypo
     fonts:
       - asset: fonts/Entypo.ttf
         weight: 700
   - family: EvilIcons
     fonts:
       - asset: fonts/EvilIcons.ttf
         weight: 700
   - family: Feather
     fonts:
       - asset: fonts/Feather.ttf
         weight: 700
   - family: FontAwesome
     fonts:
       - asset: fonts/FontAwesome.ttf
         weight: 700
   - family: Foundation
     fonts:
       - asset: fonts/Foundation.ttf
         weight: 700
   - family: Roboto-Regular
     fonts:
       - asset: fonts/Roboto-Regular.ttf
         weight: 400
   - family: NotoSans-Regular
     fonts:
       - asset: fonts/NotoSans-Regular.ttf
         weight: 700
   - family: Lato-Light
     fonts:
       - asset: fonts/Lato-Light.ttf
         weight: 300
